version: '3.8'

services:
  web:
    image: 727646501048.dkr.ecr.us-east-1.amazonaws.com/django-link-shortener:latest
    command: >
      sh -c "mkdir -p /app/data && 
             python manage.py migrate --noinput && 
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    ports:
      - "80:8000"
    volumes:
      - django_data:/app/data
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=3.229.113.216,localhost
      - SECRET_KEY=django-insecure-prod-key-123

volumes:
  django_data:
